### PR TITLE
Fix farm's time left

### LINKED ISSUE #26: Time left only rendering `days`
In My Farms, Deposit & Withdrawal views we have 'Time Left' which is taken from a value of type `TimeRemaining` that returns an object with the amount of `months, days, hours, minutes, seconds` - for some reason if the farm has more than 1 month remaining it only displays the number of days after 1 month.

Current Behavior:
```
{
 months: 1,
 days: 14
}
```
Time Left: 14 days

Expected Behavior:
```
{
 months: 1,
 days: 14
}
```
Time Left: 34 days (can vary depending on the current month)

### PR DESCRIPTION
**Pull request by crisog**
Closes #26.

Builds on #25.

### CODE REVIEW

File: src/views/DepositWithdraw/components/DepositInfo/index.tsx [hunk 1]
```diff
@@ -75,8 +75,8 @@ export const DepositInfo: React.FC<IDepositInfo> = ({ farmSelected }) => {
         <SmallInfoCard
           iconType={'question'}
           statTitle={'time left'}
-          statContent={`${timeRemaining?.days} days left`}
-          statFill={formatFillPercentage(timeRemaining, totalTime)}
+          statContent={`${formatDaysFromTimestamp(timeLeft).toFixed(0)} days left`}
```
Comment (ECWireless) [inline src/views/DepositWithdraw/components/DepositInfo/index.tsx]: Is `toFixed(0)` necessary here? Won't `timeLeft` always return an integer?

File: src/views/DepositWithdraw/components/WithdrawInfo/index.tsx [hunk 2]
```diff
@@ -111,8 +111,8 @@ const WithdrawFarm: React.FC<IWithdrawFarm> = ({ address, farmSelected }) => {
           <SmallInfoCard
             iconType={'caret'}
             statTitle={'Time Left'}
-            statContent={`${timeRemaining?.days} days left`}
-            statFill={formatFillPercentage(timeRemaining, totalTime)}
+            statContent={`${formatDaysFromTimestamp(timeLeft).toFixed(0)} days left`}
```
Comment (ECWireless) [inline src/views/DepositWithdraw/components/WithdrawInfo/index.tsx]: Same comment as above.

File: src/views/MyFarms/index.tsx [hunk 3]
```diff
@@ -126,8 +126,8 @@ const MyFarms: React.FC = () => {
                 <SmallInfoCard
                   iconType={'question'}
                   statTitle={'Time Left'}
-                  statContent={`${timeRemaining?.days} Days`}
-                  statFill={formatFillPercentage(timeRemaining, totalTime)}
+                  statContent={`${formatDaysFromTimestamp(timeLeft).toFixed(0)} Days`}
```
Comment (ECWireless) [inline src/views/MyFarms/index.tsx]: Same ^

File: src/views/Stats/index.tsx [hunk 4]
```diff
@@ -104,7 +104,7 @@ const Stats: React.FC = () => {
                   size={'sm'}
                 />
                 <MediumInfoCard
-                  amount={`${formatDaysFromTimestamp(totalTime)} Days`}
+                  amount={`${formatDaysFromTimestamp(totalTime).toFixed(0)} Days`}
```
Comment (ECWireless) [inline src/views/Stats/index.tsx]: Same as above.

File: src/views/DepositWithdraw/components/DepositInfo/index.tsx (hunk 1 above)
Comment (crisog) [reply src/views/DepositWithdraw/components/DepositInfo/index.tsx]: After `formatDaysFromTimestamp(timeLeft)` it returns days including lots of decimals. And it's not practical to have 45.454853945 days left.

Comment (ECWireless) [reply src/views/DepositWithdraw/components/DepositInfo/index.tsx]: Ah, right, I mistakenly thought you were calling `toFixed(0)` on `timeLeft`, not `formatDaysFromTimestamp()`.

Maybe the function should just be changed to:
```
export function formatDaysFromTimestamp(totalTime?: number): number {
  if (totalTime && totalTime !== 0) {
    const durationDays = totalTime / 86400;
    return Math.round(durationDays);
  } else {
    return 0;
  }
}
```
... so that we don't have to append `toFixed(0)` every time we use it.

Comment (crisog) [reply src/views/DepositWithdraw/components/DepositInfo/index.tsx]: Sure, that sounds way better

**Review by ECWireless — APPROVED** [review]
